### ISSUE TITLE
There is no documentation for using this module

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-versioned-admin#60]
Please add some documentation. E.g. How to add a history view to ones model via https://github.com/silverstripe/silverstripe-versioned-admin/blob/master/src/Forms/HistoryViewerField.php

## Tasks

* Add history viewer docs to https://docs.silverstripe.org/en/4/developer_guides/model/versioning/
* Add note to the changelog for 4.3.0
* Update https://userhelp.silverstripe.org/en/4/creating_pages_and_content/pages/rolling_back_pages/
* [Add versioned-admin to api.silverstripe.org](https://github.com/silverstripe/api.silverstripe.org/issues/81)

## Pull requests

- [x] https://github.com/silverstripe/api.silverstripe.org/pull/82
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8606
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/86

**Comment by chillu** [comment]
@brynwhyman @NightJar Could we make this part of the 2.2.0 release please? It should be in the DoD for the team to have a feature documented for developers, right? And this is a high profile feature that we want to encourage devs to use. We've just got feedback from one of our partner agencies that they have no idea on how to apply the history viewer to their own views, and it's far from straightforward:

- Add the HistoryViewerField to your DataObject's CMS fields
- Define GraphQL scaffolding to expose the necessary DB fields
- Add a GraphQL query (Javascript) and apply it to the HistoryViewer component with JS Injector transformation

This should be called out both in the 4.3.0 upgrading guide, and the https://docs.silverstripe.org/en/4/developer_guides/model/versioning/ docs.

**Comment by chillu** [comment]
Changing from `impact/low` to `impact/high` since a feature which devs can't use (because of lacking docs) is of much lower value

**Comment by brynwhyman** [comment]
Don't worry @chillu it's in our 2.2.0 milestone. Ideally this would have been done during development, but we'll make sure it's included before it's released. Good point on adding something to the upgrade guide too.

I'll check in with @clarkepaul on the user help and see where we're at.

**Comment by clarkepaul** [comment]
Cheers for flagging this, I'll add a task to get that covered. Is it best to get input with each release with what UI has changed or maybe we make it part of the OSers DoD for each modification? I add a reminder to the DoD anyway.

**Comment by robbieaverill** [comment]
It looks like the userhelp part of this is already in flight with @sachajudd in https://github.com/silverstripe/silverstripe-userhelp-content/issues/129, so I'll stay away from it for now =)

PRs are up for the dev docs and adding versioned-admin to the API site

**Comment by robbieaverill** [comment]
I ran into a conflict with elemental. Something that I remember thinking about at the time but pressed on with because we were pressed for time and had limited understanding of it at the time: https://github.com/dnadesign/silverstripe-elemental/issues/497

**Comment by NightJar** [comment]
@robbieaverill 	could you perhaps please add a PR here from e.g. the readme to the docs you've got open in the `framework` PR?
I think that'd go a long way.

**Comment by robbieaverill** [comment]
Sure, I’ll update the existing link to point directly to the relevajt content

**Comment by ScopeyNZ** [comment]
All PRs merged 🙂
